[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[build-dependencies]
witx-bindgen = { git = "https://github.com/bytecodealliance/wasi.git" }

[dependencies]
anyhow = "1"

serde = "1"
serde_json = "1"

base64 = "0.13"

[lib]
crate-type = ["lib", "cdylib"]
