interface host-to-core-unstable {
  abort: func()

  record http-header-entry {
    key: string,
    value: string
  }  
  http-get: func(url: string, headers: list<http-header-entry>) -> u32
  http-response-headers: func(handle: u32) -> list<http-header-entry>
  http-response-read: func(handle: u32, out: list<u8>) -> u32
}

world core {
  import sf-unstable: host-to-core-unstable
  export sf-unstable-exp: host-to-core-unstable
}

